module.exports = `
  type Recipe {
    _id: String
    title: String
    description: String
    servings: String
    ingredients: [String]
    steps: [String]
    notes: String
    source: String
    user: User!
  }

  type User {
     _id: String
    name: String
    email: String!
    jwt: String
    recipes: [Recipe] 
  }

  type Query {
    allRecipes: [Recipe]
    recipe(_id:String!):Recipe
    allUsers: [User]
  }

  type Mutation {
    addRecipe(
        title: String!
        description: String!
        servings: String!
        ingredients: [String]
        steps: [String]
        notes: String!
        source: String!
    ):Recipe
    updateRecipe(
      _id:String!
      title: String!
      description: String!
      servings: String!
      ingredients: [String]
      steps: [String]
      notes: String!
      source: String!
    ):Recipe
    deleteRecipe(
      _id:String!
    ):Recipe
    register (
      name: String!
      email: String!
      password: String!
    ):User
    login (
      email: String!
      password: String!
    ):User
  }
`